DROP TABLE IF EXISTS upload;
DROP SEQUENCE IF EXISTS upload_id_seq;

CREATE SEQUENCE IF NOT EXISTS upload_id_seq;
CREATE TABLE upload (
    id SERIAL PRIMARY KEY,
    title VARCHAR( 100 ) NOT NULL
);
